version: '3'

services:
  library-be:
    image: 'library-be'
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: library-be-app
    ports:
      - "5000:8080"
    depends_on:
      - library-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-db:5432/library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  library-db:
    ports:
        - "5001:5432"
    image: 'postgres:13.1-alpine'
    container_name: library-db
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
