spring:
  application:
    name: Library
  profiles:
    active: dev
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username:
    password:
    hikari:
      pool-name: Library-DB
